### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by tiagopc** [ashthornton-gc/asscroll#3]
Can you please add more explaination in Installation section? i'm having problem to install this. Is there any way to simply install by calling script in the page?

**Comment by ashthornton-gc** [comment]
Currently you will need a JS compiler like Webpack to import this into your setup. I do need to fix the compiled version in the dist folder so that the main var is exposed. Once I've done that, you should be able to include the script on a page and use it that way, although you'd be better off using it as a module anyway.

**Comment by tiagopc** [comment]
Ok, thanks a lot for answering!
